"""empty message

Revision ID: 6e8ae10b1a60
Revises: cca224d6d71f
Create Date: 2023-03-31 16:11:28.467540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8ae10b1a60'
down_revision = 'cca224d6d71f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_dogs_playdates',
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('playdates_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.ForeignKeyConstraint(['playdates_id'], ['playdates.id'], )
    )
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('playdates', schema=None) as batch_op:
        batch_op.drop_constraint('playdates_owner2_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('playdates_dog1_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('playdates_owner1_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('playdates_dog2_id_fkey', type_='foreignkey')
        batch_op.drop_column('dog2_id')
        batch_op.drop_column('dog1_id')
        batch_op.drop_column('owner2_id')
        batch_op.drop_column('owner1_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playdates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner1_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('owner2_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('dog1_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('dog2_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('playdates_dog2_id_fkey', 'dogs', ['dog2_id'], ['id'])
        batch_op.create_foreign_key('playdates_owner1_id_fkey', 'owner', ['owner1_id'], ['id'])
        batch_op.create_foreign_key('playdates_dog1_id_fkey', 'dogs', ['dog1_id'], ['id'])
        batch_op.create_foreign_key('playdates_owner2_id_fkey', 'owner', ['owner2_id'], ['id'])

    with op.batch_alter_table('owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    op.drop_table('owner_dogs_playdates')
    # ### end Alembic commands ###
