"""empty message

Revision ID: b784b9cf43ac
Revises: 197a8c918f14
Create Date: 2023-03-17 20:13:02.885963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b784b9cf43ac'
down_revision = '197a8c918f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('temperament', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('chip_number', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(precision=2), nullable=False),
    sa.Column('neutered_or_spayed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chip_number')
    )
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dog_breed',
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.PrimaryKeyConstraint('dog_id', 'breed_id')
    )
    op.create_table('owner_dogs',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('dog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'dog_id')
    )
    op.create_table('playdates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dog1_id', sa.Integer(), nullable=False),
    sa.Column('dog2_id', sa.Integer(), nullable=False),
    sa.Column('owner1_id', sa.Integer(), nullable=False),
    sa.Column('owner2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dog1_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['dog2_id'], ['dogs.id'], ),
    sa.ForeignKeyConstraint(['owner1_id'], ['owner.id'], ),
    sa.ForeignKeyConstraint(['owner2_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('playdate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playdate_id'], ['playdates.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['owner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('message')
    op.drop_table('playdates')
    op.drop_table('owner_dogs')
    op.drop_table('dog_breed')
    op.drop_table('owner')
    op.drop_table('dogs')
    op.drop_table('breeds')
    # ### end Alembic commands ###
